# Generated by Django 3.1 on 2020-08-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0002_auto_20200821_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('contact_phone', models.IntegerField(verbose_name='Contact Number')),
                ('address', models.CharField(max_length=80, verbose_name='Adress')),
                ('base', models.CharField(choices=[('AGP', 'Malaga'), ('EDI', 'Edinburgh'), ('TFS', 'Tenerife South'), ('PVD', 'Providence'), ('DUB', 'Dublin')], max_length=3, verbose_name='Base')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
            ],
        ),
    ]
