# Generated by Django 3.1 on 2020-08-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_employee_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_infos',
            new_name='employee_cv',
        ),
    ]
