# Generated by Django 3.1 on 2020-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200822_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full name'),
        ),
    ]
