# Generated by Django 3.1 on 2020-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('alt_name', models.CharField(max_length=20, verbose_name='Short Name')),
                ('in_use', models.BooleanField(default=True, verbose_name='In use')),
            ],
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
