# Generated by Django 3.1 on 2020-08-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_auto_20200821_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='field_name',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('field_name', 'alt_name')},
        ),
    ]
